name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for Python 3.13.5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: cp313-*
          CIBW_ARCHS: "auto"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BUILD_VERBOSITY: 1
        with:
          output-dir: wheels

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-py3.13
          path: ./wheels