name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Find MinGW bin path
        shell: pwsh
        run: |
          $mingwPath = Get-ChildItem -Path "C:\ProgramData\chocolatey\lib\mingw\tools\install" -Filter "mingw64" -Recurse -Directory -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName | Select-Object -First 1
          if ($mingwPath) {
              $mingwBinPath = Join-Path $mingwPath "bin"
              echo "Found MinGW bin path: $mingwBinPath"
              echo "MINGW_BIN_PATH=$mingwBinPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
              Write-Error "MinGW bin path not found!"
              exit 1
          }

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: cp310-*
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: 'delvewheel repair -w {dest_dir} {wheel} --add-path "${{ env.MINGW_BIN_PATH }}"'
        with:
          output-dir: wheels

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheels