name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cc: [gcc, clang]
        exclude:
          # Clang on Windows requires extra setup to work with make
          # and is not included in this basic setup.
          - os: windows-latest
            cc: clang

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install Make on Windows
      if: runner.os == 'Windows'
      run: choco install make

    - name: Build project
      run: make CC=${{ matrix.cc }}

    - name: Test project (run executable)
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          ./CHILS.exe -h
        else
          ./CHILS -h
        fi

    - name: Clean up
      run: make clean